name: CI

on: [push]

jobs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: apt dependencies
      run: |
        sudo add-apt-repository ppa:joseluisblancoc/gtsam-develop -y
        sudo add-apt-repository universe
        sudo apt update
        sudo apt-get install -y lcov gcovr libboost-all-dev libeigen3-dev libgtsam-dev
    - name: "do tests"
      run: |
        mkdir build 
        cd build
        cmake .. 
        make check   